### ISSUE TITLE
add readme and cli docs for each package

### ISSUE THREAD

**Issue by goastler** [prosopo/captcha#114]

**Comment by HughParry** [comment]
This isn't actionable - needs to be broken up into tickets like, e.g.

Write README for X package

Acceptance Criteria:

- Explains how to run command Y
- Details how to set up docker for Z

**Comment by HughParry** [comment]
@goastler to turn into ticket per package, with above format for AC then close this one

**Comment by forgetso** [comment]
lots of small issues created
