### ISSUE TITLE
provider and dapp should store their accountid in the struct

### ISSUE THREAD

**Issue by goastler** [prosopo/captcha#115]

**Comment by goastler** [comment]
this would make handling individual providers/dapps easier, as the account is in their struct. However, would duplicate inforamtion ever so slightly in mappings, as the key (account id) is also in the value (e.g. dapp containing account id)

**Comment by goastler** [comment]
would take more gas in terms of storage, but there was other reasons that I can't remember for doing this, so research

**Comment by HughParry** [comment]
Moving to low priority - not an issue for now
