### ISSUE TITLE
missing dist folder

### ISSUE THREAD

**Issue by TanyaStere42** [prosopo/captcha#1460]
While evaluating this tool for integration, we found that you're missing the `/dist` folder as of 2.1.2. This makes your react solution unusable. Are you no longer supporting react?

**Comment by forgetso** [comment]
Hi @TanyaStere42, thanks for this report. We do still support React. We're investigating this as a matter of urgency and will post a resolution soon.

**Comment by forgetso** [comment]
Hi @TanyaStere42 please will you check version 2.1.6 and let me know if its working for you? Thanks.

**Comment by TanyaStere42** [comment]
Think we're good now 👍

**Comment by forgetso** [comment]
Awesome, thanks for letting us know.
