### ISSUE TITLE
getting "Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node" from react

### ISSUE THREAD

**Issue by erinz2020** [prosopo/captcha#1461]
hi I'm trying to use procaptcha in react and I'm getting following error, 

`Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node
`
my react component is pretty simple, all code is as following， do you happen to know what the error is about? Thanks

  ```
const captchaRef = useRef(null);
  useEffect(() => {
    let isCaptchaRendered = false;

    const loadProCaptcha = async () => {
      if (isCaptchaRendered || !captchaRef.current) return;

      const { render } = await import('https://js.prosopo.io/js/procaptcha.bundle.js');

      render(captchaRef.current, {
        siteKey: '5FNwzzqEhmxNk4jeWLeteBCSd696DEX9YbttnsjJ6XkhbWCL',
        callback: onCaptchaVerified,
      });

      isCaptchaRendered = true;
    };

    loadProCaptcha();

    return () => {
      if (captchaRef.current) {
        captchaRef.current.innerHTML = '';
      }
      isCaptchaRendered = false;
    };
  }, []);

  const onCaptchaVerified = async (output) => {
    console.log('Captcha verified, output: ' + JSON.stringify(output));
    const payload = { procaptchaValue: output };

    try {
      const res = await fetch('/ReCAPTCHA', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify(payload),
      });
      const data = await res.json();
      console.log('Response data: ', data);
    } catch (error) {
      console.error('Error submitting captcha: ', error);
    }
  };

return (
    <Container>
<div id="procaptcha-container" ref={captchaRef}></div>
    </Container>
  );
});

export default ReportEncounter;
```

**Comment by forgetso** [comment]
Hi @erinz2020, thank you for your report. We're investigating this issue and will respond with a resolution soon.

**Comment by forgetso** [comment]
Hi @erinz2020, please will you check version 2.1.6 and let me know if its working for you? Thanks.

**Comment by erinz2020** [comment]
hi @forgetso the above error is not caused by the npm packages, it occurred when I was importing the script('https://js.prosopo.io/js/procaptcha.bundle.js') and running inlocalhost:3000

and I also tried to install procaptcha packages, the latest package size seems perfect, however I encountered some errors about deprecated assert keyword error, which indicates that we should install a babel plugin @babel/plugin-syntax-import-attributes to resolve the deprecated assert syntax issue, I tried to install but the plugin could not be loaded successfully, it might have something to do with webpack react-app-rewired and create-react-app of our projects, so given the fact that procaptcha is working well in my production server(although I see the removeChild error in localhost:3000), I'm fine with working with procaptcha in this way: `const { render } = await import('https://js.prosopo.io/js/procaptcha.bundle.js');`

thank you for your help!

![image](https://github.com/user-attachments/assets/1e21dd43-8d9b-4775-8496-25a74cc33cba)

**Comment by forgetso** [comment]
Hey @erinz2020, we have an example with webpack here: https://github.com/prosopo/procaptcha-react-webpack

Please take a look and let me know if you're still hitting issues.

Thanks!

**Comment by forgetso** [comment]
Regarding importing the script using `await import`, this is a slightly abnormal approach. [Usually, it's just added via a `<script>` tag](https://docs.prosopo.io/en/basics/client-side-rendering/). We'll try to take a look at this approach and see if we can recreate the error locally.

**Comment by erinz2020** [comment]
> Hey @erinz2020, we have an example with webpack here: https://github.com/prosopo/procaptcha-react-webpack
> 
> Please take a look and let me know if you're still hitting issues.
> 
> Thanks!

sure, I'll check out later, thanks!

**Comment by erinz2020** [comment]
> Regarding importing the script using `await import`, this is a slightly abnormal approach. [Usually, it's just added via a `<script>` tag](https://docs.prosopo.io/en/basics/client-side-rendering/). We'll try to take a look at this approach and see if we can recreate the error locally.

I tried with adding a script tag, it worked the same as `const { render } = await import('https://js.prosopo.io/js/procaptcha.bundle.js');`

I‘m only seeing the "removeChild" on localhost:3000, on production env it's working well

**Comment by erinz2020** [comment]
I'm going to close this issue since it's working well with production
