### ISSUE TITLE
api port duplicated in env

### ISSUE THREAD

**Issue by goastler** [prosopo/captcha#154]

**Comment by goastler** [comment]
`API_PORT` is one env variable, but `API_BASE_URL` contains the port too. It would be better to have a single variable to control the port, i.e. eliminate the port from `API_BASE_URL` or remove `API_PORT` altogether

**Comment by HughParry** [comment]
Related to larger env organise work

**Comment by forgetso** [comment]
Should be part of https://github.com/prosopo/captcha-private/issues/497
