### ISSUE TITLE
collect data for demo

### ISSUE THREAD

**Issue by goastler** [prosopo/captcha#164]

**Comment by goastler** [comment]
we need one or more datasets for the demo.

Should we:
- take a fully labelled dataset
- split it into labelled and unlabelled
- serve this data at the demo
- collect labelling from the demo
- compare labelling from the demo against the known labels, thus able to compute accuracy, etc.
Might make a nice statistic for advertising / enticing clients?

**Comment by forgetso** [comment]
Questions
- if 100k images and < 1% are dog, how do we ensure that a dog is in the unlabelled captcha when target is dog?
   - unlabelled captchas are combinations of labelled and unlabelled images to ensure there is at least one of the target
- how quickly can we label data and to what degree of accuracy?

**Comment by goastler** [comment]
closed in favour of smaller issues. We've already got the dataset now, just need to make it square images only. As for how quickly the data can be labelled, I've added that as it's own issue prosopo/captcha-private#767
