### ISSUE TITLE
Select "None" button

### ISSUE THREAD

**Issue by goastler** [prosopo/captcha#165]

**Comment by goastler** [comment]
Make a select "None" button for the case where there are no images matching the label in a captcha. Depending on the dataset generation parameters, this may occur in the labelled captcha and will most likely occur in the unlabelled data

**Comment by goastler** [comment]
This button should simply set the `solutions` array to `[]` and move onto the next captcha round. Purely a frontend change

**Comment by forgetso** [comment]
We have a captcha with no matching images (Select car in one of them where there are no cars) and the solution is to not click anything. Does this not suffice?

**Comment by goastler** [comment]
make a little js to rename the submit button to "none" when no selection is made
