### ISSUE TITLE
simplify typechain usage for queries and tx

### ISSUE THREAD

**Issue by goastler** [prosopo/captcha#169]

**Comment by goastler** [comment]
currently the typechain return types are a massive pain. Can we make this better? probably.

E.g. having to handle `ReturnNumber` type currently

**Comment by goastler** [comment]
tackle this with the js side of sr25519

**Comment by HughParry** [comment]
Part of ongoing typechain fork work

**Comment by HughParry** [comment]
Related to typechain replacement. Moving to old since limited value and needs AC

**Comment by HughParry** [comment]
Refinement - can we get any info here into the tickety stuff for typechain proposal

**Comment by HughParry** [comment]
And then close this
