### ISSUE TITLE
change terminology throughout

### ISSUE THREAD

**Issue by goastler** [prosopo/captcha#244]

**Comment by goastler** [comment]
- dapp_user -> user

anything else?

**Comment by goastler** [comment]
prosopo/captcha#172

**Comment by goastler** [comment]
- captcha_solution_commitment -> commit
- dapp -> app
- operator -> admin

**Comment by HughParry** [comment]
Note:

e.g. contract has dappAccount whereas js has dapp

"[rename JS contract variables to match](https://github.com/prosopo/captcha/issues/172)"

**Comment by HughParry** [comment]
Note:

[Change contract to account in dapp_register, DappConfig and other locations](https://github.com/prosopo/captcha-private/issues/636)

**Comment by HughParry** [comment]
Need to agree on terminology as team before changes

**Comment by HughParry** [comment]
Closing since very old, dupe of https://github.com/prosopo/captcha/issues/172, needs refinement (what terminology needs changing), etc

**Comment by HughParry** [comment]
Didn't mean to reopen this
