### ISSUE TITLE
ignore polkadot type wasms in bundle

### ISSUE THREAD

**Issue by goastler** [prosopo/captcha#245]

**Comment by goastler** [comment]
I've read that the wasms can be missing and the polkadot types package will default back to javascript implementations. This would make the bundle smaller by quite a margin I think!

**Comment by goastler** [comment]
sr25519 is only available via the wasm bytes.

All the wasms are chucked into a single byte array in js as a string, there's no easy way to drop specific fns, so we end up carrying around unused fns like keccak, sha512, etc.

I can't get wasm-crypto to build

They do have a rollup config suggesting you can drop some fns to reduce bundle size, but I can't get that working without a build

Could contact the guy who maintains it, iirc it's jako

**Comment by forgetso** [comment]
Or switch to something other than PolkadotJS - see ticket talking about smoldot / provider

**Comment by HughParry** [comment]
Bundle size isn't a blocker for us right now. Moving to low priority

**Comment by HughParry** [comment]
eh
