### ISSUE TITLE
change account prefixes in contract testing

### ISSUE THREAD

**Issue by goastler** [prosopo/captcha#251]

**Comment by goastler** [comment]
[0x0; 32] and [0x1; 32] are used by default in the testing environment, which can leads to issues by duplication of accounts or calling from the default [0x1; 32] when that accounts has been used as a role, e.g. provider, leading to pass or fail of tests when they shouldn't.

We either need to add a constant at the end of our test accounts or change the prefixes. I think the former would be better, otherwise we're always open to a clash in the future if someone forgets about this issue

**Comment by goastler** [comment]
pretty sure this is done, but I need to check

**Comment by HughParry** [comment]
Refinement since I can't tell if it's done or not. Screenshot to explain



![Image](https://github.com/prosopo/captcha/assets/90424587/578521d5-53d0-4f5f-a5e4-e2fe2476a15e)

**Comment by HughParry** [comment]
@goastler to add context about why needed

**Comment by goastler** [comment]
basically, we need alice/bob/etc to be the same in js as in rust. It's not, and we could do with having some way of deriving accounts on both rust and js which produces the same account in both ecosystems in a determiniistic way
