### ISSUE TITLE
decide on process for updating images on flux nodes

### ISSUE THREAD

**Issue by goastler** [prosopo/captcha#253]

**Comment by goastler** [comment]
Currently, flux takes a while to deploy a new docker image. We've got our images in that docker image with a lightweight image server running. Due to flux taking an undisclosed and variable amount of time to switch over to using the new docker image with a new set of images in, we get 404s in the meantime when pointing at the new dataset and vice versa when the flux node has updated but we're still using the old dataset.

Further, a single flux node upgrades quicker than the other 2 nodes as that's the one that handled the redeploy request. The other 2 can take up to 24hrs to redeploy, leaving the state where one node has the new set of images and the other two don't. The it's down to which node you are load-balanced to as to whether you can reach the old images or new images.

How do we handle this?

I can think of two options:
1. run a new flux node per dataset release
    this would leave the old flux node still running and doing nothing, wasting resources. We could reuse it for something else, but what?
3. integrate the new images with the old images
    this would be a 3 step process. 1) add the new images to the docker image, do a redeploy and wait for all nodes to redeploy (up to 24hrs). 2) switch the dataset json on the provider to use the new images. 3) remove the old images from the docker image, upload, wait for flux redeploy (up to 24hrs). This entire process could take anywhere from 2-48hrs according to flux docs on timeline of redeploys. However, no wasted resources and no url changes (i.e. my-img-server.app.runonflux.io stays the same, obviously the image files have changed)

**Comment by goastler** [comment]
option 3 from chris:
"switch over to the github demo dataset, switch docker imgs, wait for propagation, then switch back to original url for flux nodes"

**Comment by goastler** [comment]
will be switching the imgs again to squares so good opportunity to give option 2 a try

**Comment by goastler** [comment]
option 4 from chris, ssh into each node and pull the new docker img

**Comment by goastler** [comment]
option 5 from hugh, soft reploy each node

**Comment by HughParry** [comment]
Will give 2 a try when sorting the letterbox fix ticket

**Comment by forgetso** [comment]
Testing the docker image upgrade procedure currently.

**Comment by forgetso** [comment]
Strategy: add to the existing image, push it back up to docker and soft redeploy. Wait for new images to come online then update the datasets in providers.
