### ISSUE TITLE
weighted labelling

### ISSUE THREAD

**Issue by goastler** [prosopo/captcha#297]

**Comment by goastler** [comment]
hugh's idea

e.g. given 4 correct/incorrect imgs then 14 unlabelled imgs which have been labelled, but not much of a human test, so could be a bot still, so labels are only somewhat reliable

however, given 15 correct/incorrect imgs then 3 unlabelled imgs which have been labelled, 15 is quite a good human test so labels should be reliable

this should be recorded in the label collection process somehow. E.g. via a weighting, perhaps.

**Comment by HughParry** [comment]
I think potentially this could be simply weighed on the probability that each of the labelled images was randomly independently correctly labelled. So, weighting then 1 - that prob, i.e. for the number of labelled images in the dset it would then be

1. 0.5
2. 0.75
3. 0.94
4. 0.98
5. 0.99

Then 6+ are all so close to 1 that we can discount random guessing.

Scope to be more sophisticated here, but I feel this is a decent starting point

**Comment by goastler** [comment]
I actually really like that system, but I'm not sure about the maths, could you show your working?

My thoughts were say we've got 3 images in a captcha, there's 6 permutations of what the solutions can be. So choosing a solution at random would give me 1/6 chance of being correct. Doing the 1 - prob yields the following weightings for number of labelled images in the captcha (formula `1 - 1/2^n`):
1. 0.5
2. 0.75
3. 0.875
4. 0.9375
5. 0.96875
6. 0.984375
7. 0.9921875
8. 0.99609375
9. 0.998046875
Similar situation to you where 6-7 and above are ~1.

Something to bare in mind is that the user has to do this twice due to the two rounds of the captcha. In addition, there should always be 1 correct and 1 incorrect image per captcha, which is 2 labelled images per captcha, thus 4 in total across both rounds. The weightings using both rounds (i.e. aggregating the number of labelled images and thus probability of getting them all correct) would be 0.9375 or more, so I'm not sure if there's much point in doing the weightings anymore given our captcha constraints of min 1 incorrect and min 1 correct per round make the likelihood of randomly guessing the permutation very unlikely.

The above weights also assume that the user knows where the labelled images are in the captcha. If we remove that assumption, it's an nCr problem. E.g. say there is 4 labelled images in the captcha containing 9 images. I've got to do the nCr, i.e. from 9 choose 4, then also get the permutation of solutions correct. For `r` labelled images in the captcha, the nCr is below:
|r|nCr|1/nCr|(1/nCr)*(1/2^r)|
|---|---|---|---|
|0|1|1|1|
|1|9|0.111111111|0.055555555|
|2|36|0.027777778|0.006944445|
|3|84|0.011904762|0.001488095|
|4|126|0.007936508|0.000496032|
|5|126|0.007936508|0.000248016|
|6|84|0.011904762|0.000186012|
|7|36|0.027777778|0.000217014|
|8|9|0.111111111|0.000046503|
|9|1|1|0.001953125|

We should have min 1 correct and min 1 incorrect per round, so no less than 4 labelled images per captcha challenge. This means there's less than 0.2% chance of a user randomly picking the labelled images **and** picking the correct solution. Thus I feel like the weightings are defunct now we're sure the user is human because it's incredibly unlikely they would pass via random picking.

@HughParry does the maths here make sense and do you agree?

**Comment by forgetso** [comment]
We don't need this since we have rounds with different numbers of correct  / incorrect captcha.
