### ISSUE TITLE
contact zooniverse to ask how they process their labels

### ISSUE THREAD

**Issue by goastler** [prosopo/captcha#298]

**Comment by goastler** [comment]
it's important for us to find out how they process their labelled data in order to align with their processes. However, I believe pumping out some kind of json containing the collected labels should be sufficient, as anyone processing labels should be able to handle this

**Comment by HughParry** [comment]
Update - zooniverse contact has moved to Australian outback

**Comment by forgetso** [comment]
Have contacted contact@zooniverse.org
