### ISSUE TITLE
use events method of doing callbacks on client website with bundle

### ISSUE THREAD

**Issue by goastler** [prosopo/captcha#302]

**Comment by goastler** [comment]
in addition to the current way of passing callbacks via the fn name

**Comment by forgetso** [comment]
`dispatchEvent('ProcaptchaBlah')`

**Comment by forgetso** [comment]
`addEventListener('ProcaptchaBlah')`

**Comment by forgetso** [comment]
Low priority as we have a way of doing it already.

**Comment by forgetso** [comment]
Closing as we can do this if asked.
