### ISSUE TITLE
what happens to the fingerprinting mechanism if the canvas capability is disabled in the browser?

### ISSUE THREAD

**Issue by goastler** [prosopo/captcha#311]

**Comment by HughParry** [comment]
https://www.mdpi.com/1424-8220/23/6/3087

**Comment by HughParry** [comment]
Results from BrowserLeaks.com using Brave:

1. Canvas fingerprint is always unique
2. Canvas fingerprint is different between page loads
3. The file size, number of canvas, png headers all change

Unique information may still be leaked, but a naive approach to these canvas renders is different between renders

Results from fingerprint.com using Brave:

1. Fingerprint is correct and maintained between loads, incognito vs regular, vpn on vs off (only tested with free VPNs)
2. When fingerprinting is switched to strict mode, the ID changed, but is then internally consistant between loads, VPN usage, incognito on vs off
3. Blocking JS breaks the demo:

![Image](https://github.com/prosopo/captcha/assets/90424587/b8ff0f6b-b704-4362-922c-43ef9b3fbb30)

4. Maxing out the security settings in Brave, other than disabling JS seems to result in consistent IDs:



![Image](https://github.com/prosopo/captcha/assets/90424587/44cd7bbb-ef6f-4c5c-9b8f-23367db924c0)

**Comment by HughParry** [comment]
This is also persistent between cache cleaning and reboots. Some good discussion here

https://github.com/kkapsner/CanvasBlocker/issues/643

**Comment by HughParry** [comment]
fingerprint.com fails every time for TOR as expected

**Comment by HughParry** [comment]
Brave consistently gives uniques on this site https://amiunique.org/fingerprint

**Comment by HughParry** [comment]
Potentially linked issue here https://github.com/prosopo/captcha/issues/334

**Comment by HughParry** [comment]
Most frictionless bot detection appears to be able to function with canvas disabled - some more good info here https://github.com/niespodd/browser-fingerprinting
