### ISSUE TITLE
Create releases for experimental/stable versions to agreed schedule

### ISSUE THREAD

**Issue by forgetso** [prosopo/captcha#337]
# Triggers

- Experimental release - PR into main with -beta post fix on release number.
- Stable release - PR into main with no post fix on release number.

# What are we releasing?

- [ ] docker images
  - release to docker hub - bear in mind Flux will update on push to `latest` tag
- [x] npm packages
  - release to npm registry
- [ ] contracts and their sources
  - release to Releases page
- [ ] JS bundles
  - release to our docker image and push to docker hub, Flux will auto update
  - release to releases page

Each of the above should be an individual ticket.

# What's our next release number?

`0.1.16` - current npm
`0.1.17` - next npm + everything

# Experimental vs Release numbering

Experimental version numbering should be post-fixed with `-beta`, e.g. `0.1.17-beta`

**Comment by goastler** [comment]
not doing -beta stuff anymore, just use patch version
