### ISSUE TITLE
investigate substrate errors in react

### ISSUE THREAD

**Issue by goastler** [prosopo/captcha#44]
When building the app, ~20 errors come from substrate not being able to find files.

E.g.
`WARNING in ../../node_modules/@substrate/connect-extension-protocol/dist/cjs/index.js
Module Warning (from ../../node_modules/source-map-loader/dist/cjs.js):
Failed to parse source map from '/home/geopro/bench/workspaces/node_modules/@substrate/connect-extension-protocol/src/index.ts' file: Error: ENOENT: no such file or directory, open '/home/geopro/bench/workspaces/node_modules/@substrate/connect-extension-protocol/src/index.ts'`
Failed to parse source map from '/home/geopro/bench/workspaces/node_modules/@substrate/connect/src/index.ts' file: Error: ENOENT: no such file or directory, open '/home/geopro/bench/workspaces/node_modules/@substrate/connect/src/index.ts'`
`

**Comment by goastler** [comment]
might be because I do not have substrate connect extension installed whereas @forgetso does. Try installing and see if these messages disappear

**Comment by forgetso** [comment]
@goastler was this resolved?

**Comment by forgetso** [comment]
Cannot replicate.

**Comment by goastler** [comment]
can't replicate, call it fixed
