### ISSUE TITLE
add timeout to dapp

### ISSUE THREAD

**Issue by goastler** [prosopo/captcha#445]

**Comment by goastler** [comment]
this needs to be added js and rust side to allow dapps to specify how long a captcha should remain valid before expiring.

E.g. if I fill out a captcha and get it correct, then take 2 hours to actually click the submit button on the form, the dapp has to keep the session live for the whole of this time. The timeout is essentially "how long does the user have between completing the captcha and submitting the dapp's form"

we should probably name this more appropriately!

**Comment by forgetso** [comment]
Frontend implementation done.

**Comment by forgetso** [comment]
We think this is addressed by last_valid_captcha function in contract. However, should this verify if a given payload is valid within a timframe? e.g. commitmentId `0x1234` was completed within `n` seconds.

Task is to write down the various scenarios and the flow of data and outcomes in each test.
