### ISSUE TITLE
content moderate v2 demo dataset

### ISSUE THREAD

**Issue by goastler** [prosopo/captcha#448]

**Comment by forgetso** [comment]
Split the folders by 3 and check them manually.

**Comment by HughParry** [comment]
- [x] George: airplain - gorilla
- [x] Hugh: grand-piano - skateboard
- [x] Chris: skunk - zebra

**Comment by HughParry** [comment]
Note - up to ladder

**Comment by HughParry** [comment]
Note - up to llama
