### ISSUE TITLE
make docker image for provider

### ISSUE THREAD

**Issue by goastler** [prosopo/captcha#45]

**Comment by goastler** [comment]
should contain caddy, logrotate and a method of configuring mongodb connection

**Comment by forgetso** [comment]
should do the following
- [x] run the api
- [ ] periodically calculate solutions and update datasetId
- [ ] periodically batch solutions on-chain and update datasetId
- [ ] maintenance operations to ensure that database size does not get too large
- [ ] log details of jobs

**Comment by HughParry** [comment]
@forgetso new ticket to follow for

 periodically calculate solutions and update datasetId
 periodically batch solutions on-chain and update datasetId
 maintenance operations to ensure that database size does not get too large
 log details of jobs
