### ISSUE TITLE
make script to sign payloads on cli

### ISSUE THREAD

**Issue by goastler** [prosopo/captcha#453]

**Comment by forgetso** [comment]
we can use polkadot-js to do this using

`npx polkadotblahblah` but the payload needs to be hex

**Comment by goastler** [comment]
not sure if the cli needs hex only - was talking about the gui

**Comment by goastler** [comment]
https://github.com/polkadot-js/tools/tree/master/packages/signer-cli

wrap the above and enable passsing raw data than hex?

**Comment by forgetso** [comment]
https://github.com/polkadot-js/tools/tree/master/packages/signer-cli#polkadotsigner-cli

**Comment by HughParry** [comment]
Moving to refinement since very old - is this in progress?
