### ISSUE TITLE
Create networks package to store rococo/shiden/astar/etc info

### ISSUE THREAD

**Issue by HughParry** [prosopo/captcha#493]
Our Vite config restricts NODE_ENVIRONMENT to production or development because of dependencies. Currently we store values like rococo here for default network info.

We should move network info to a new networks package, and remove default values from env variables where possible

**Comment by goastler** [comment]
env everything package would probably be best place to start, split in future if need be - chris

**Comment by HughParry** [comment]
Linked to #529
