### ISSUE TITLE
make sure all unit tests are run for each package

### ISSUE THREAD

**Issue by goastler** [prosopo/captcha#52]

**Comment by goastler** [comment]
Does the current gh actions script go into each package and run any tests it finds? E.g. the common package has a UrlConverter which I built. It has corresponding tests. I'm not sure if these are run. If they're not, they should be

**Comment by goastler** [comment]
chris says vite isn't running all tests

**Comment by goastler** [comment]
`npm run test` runs unit tests twice, once before building and once after? we think. something to do with the vite watcher imo

**Comment by goastler** [comment]
consider tests double run when doing datasets-fs tests whcih do find-and-replace

**Comment by HughParry** [comment]
I think this works fine now. Moved to old

**Comment by HughParry** [comment]
Refinement - can we close?
