### ISSUE TITLE
Fail to start API if database is not connected

### ISSUE THREAD

**Issue by forgetso** [prosopo/captcha#530]
The provider will let you start with an undefined database and then run the API. This causes the API to emit errors like `cannot read getDatasetDetails of undefined` because it's doing `this.db.getDatasetDetails(datasetId)` within the API task. 

We need to prevent the API from running when there is no db or only allow API calls to run that do not involve the DB, returning an error otherwise.

**Comment by goastler** [comment]
make a getter which checks whether the db is defined and throw if not
