### ISSUE TITLE
Provider random selection is not working on rococo

### ISSUE THREAD

**Issue by forgetso** [prosopo/captcha#531]
There are 2 providers in the contract but only one of them is being chosen.

![Image](https://user-images.githubusercontent.com/7630866/268118514-33966012-8550-4ac6-a8b5-da796de0279c.png)

**Comment by HughParry** [comment]
For bugfix - register 3 and see how many chosen to see if off by 1 error

**Comment by HughParry** [comment]
This is just mismatch between payees for random provider selection. Sitekey for prosopo set to payee=any for now
