### ISSUE TITLE
clean out old branches from monorepo merge

### ISSUE THREAD

**Issue by goastler** [prosopo/captcha#7]

**Comment by goastler** [comment]
all branches were renamed to "<original package>/<branch name>", e.g. "my-feature" became "common/my-feature" in the common repo.

all branches were then uploaded to the monorepo. This means the monorepo has a) loads of branches and b) all of the old branches duplicated across each repo (e.g. a main branch per repo, etc) and c) all old branches which are obsolete

These all need to be purged carefully to not lose work

**Comment by HughParry** [comment]
Completed
