### ISSUE TITLE
Update typescript to version 5 when react-scripts will accept a higher version

### ISSUE THREAD

**Issue by forgetso** [prosopo/captcha#76]
Can't upgrade typescript due to this: https://github.com/facebook/create-react-app/issues/13080

**Comment by HughParry** [comment]
CRA is effectively unmaintained. We should just migrate away from CRA - Consider using Vite?

**Comment by HughParry** [comment]
We've fallen in love with Vite - @goastler bumped typescript to 5.x

**Comment by HughParry** [comment]
Done
