### ISSUE TITLE
Check most recent user verification is within maxVerifiedTime in contract

### ISSUE THREAD

**Issue by HughParry** [prosopo/captcha#782]

**Comment by HughParry** [comment]
When contract is queried like so:

```
(await contractApi.query.dappOperatorIsHumanUser(user, this.config.solutionThreshold)).value
                .unwrap()
                .unwrap()
```

We need to be able to supply it with a maxVerifiedTime, such that the contract checks the user's score and make sure they have completed a captcha within maxVerifiedTime

**Comment by forgetso** [comment]
We might be able to use the exising function below for this

```
        /// Get the last correct captcha for a user
        #[ink(message)]
        pub fn dapp_operator_last_correct_captcha(
```

**Comment by HughParry** [comment]
Addressed by this pr https://github.com/prosopo/captcha/pull/780

**Comment by goastler** [comment]
#445 related

**Comment by forgetso** [comment]
Duplicate of #445
