### ISSUE TITLE
handle flux image size limit of 2Gb for image server

### ISSUE THREAD

**Issue by goastler** [prosopo/captcha#797]

**Comment by goastler** [comment]
we're currently at 1.48gb, limit is 2gb (set by flux). options:

- use multiple flux servers, e.g. split images across many servers as necessary
- host elsewhere
- upload imgs to flux after instantiation (it's only the docker img which has the restriction on size, NOT the storage for the container, so we can set the storage to XGb and pay accordingly) - this would require some kind of upload procedure and syncing via syncthing to the other nodes in flux
-

**Comment by goastler** [comment]
@forgetso says scp and upload imgs per flux node?

**Comment by HughParry** [comment]
Not an issue - we don't currently need larger datasets. Moving to Old
