### ISSUE TITLE
switch tests to use test data from datasets-fs rather than separate github repo

### ISSUE THREAD

**Issue by goastler** [prosopo/captcha#799]

**Comment by forgetso** [comment]
Tests currently pull images from github but should probably use a local image server.

**Comment by goastler** [comment]
tests currently use the demo-datasets repo. This data has been cloned and added to (to meet minimum number of imgs per label) for the datasets-fs package, so the data can be obtained from there rather than downloading from a separate repo. I.e. the data is already local

We can run the file-server to serve the images in datasets-fs

**Comment by HughParry** [comment]
Status? At a glance I can't see where thisis going on

**Comment by HughParry** [comment]
Can we close this? What's the business value?
