### ISSUE TITLE
Configure docker network to disallow external mongodb access

### ISSUE THREAD

**Issue by goastler** [prosopo/captcha#80]
Mongo should not be accessible from outside but should be accessible from the server docker instance. The two should share a network which has no external inlet.

**Comment by HughParry** [comment]
Further info here https://stackoverflow.com/questions/39913757/restrict-internet-access-docker-container

**Comment by forgetso** [comment]
Precursor https://github.com/prosopo/captcha/issues/45

**Comment by forgetso** [comment]
No longer an issue as we've installed mongodb on the provider image
