### ISSUE TITLE
test captcha completion scenarios

### ISSUE THREAD

**Issue by goastler** [prosopo/captcha#800]

**Comment by goastler** [comment]
we need to test all the possible cases of how a captcha could be completed against when the form is submitted.

cases where user has already done a captcha:
- [ ] captcha has been completed within recency limit but not on-chain (in provider cache)
- [ ] captcha has been completed outside of recency limit but not on-chain (in provider cache)
- [ ] captcha has been completed within recency limit and is on-chain
- [ ] captcha has been completed outside of recency limit and is on-chain

cases where user is doing a captcha:
- [ ] captcha submitted within recency threshold
- [ ] captcha submitted after too long (i.e. user completes captcha and then waits 1hr to hit the submit button)

**Comment by goastler** [comment]
The factors are:
- dapp recency threshold (i.e. how old can a captcha be to be considered valid? dependent on dapp's use case / purpose)
- commit location (provider / on-chain)
- how long a user takes to submit the form in relation to completing a captcha (e.g. they do the captcha first, then take *ages* filling out the rest of the form / take a break then submit) - arguably in this case the captcha should invalidate itself and untick the box after expiry?

**Comment by HughParry** [comment]
Is this manual testing or a suite of e2es? If manual it's a simple ticket, if it's a bunch of e2es it's pretty complicated

**Comment by HughParry** [comment]
@goastler to break down into e.g. 6 individual tickets and dump them in needs refinement

**Comment by goastler** [comment]
closing, broken down into ~8 new tickets
