### ISSUE TITLE
migrate typechain to have a single file comprising all the fns available for a contract

### ISSUE THREAD

**Issue by goastler** [prosopo/captcha#804]

**Comment by goastler** [comment]
at the moment these are duplicated over "queries" and "tx". It should just be one file, call as appropriate. fns which are a tx should have some kind of gas associated in the params, whereas queries shouldn't

**Comment by HughParry** [comment]
What is the status of typechain problems like this?

**Comment by HughParry** [comment]
@forgetso Please add this under the epic for typechain proposal

**Comment by HughParry** [comment]
Refinement ^^^
