### ISSUE TITLE
remove regex hacks for typechain

### ISSUE THREAD

**Issue by goastler** [prosopo/captcha#807]

**Comment by goastler** [comment]
we have various hacks for adding bits to the typechain output via regex find-and-replace. We should remove these in favour of making the change in typechain directly

**Comment by HughParry** [comment]
What is the status of typechain problems like this?

**Comment by HughParry** [comment]
@forgetso Please add this under the epic for typechain proposal

**Comment by HughParry** [comment]
^^^ Refinement
