### ISSUE TITLE
Implement short expiry for websites

### ISSUE THREAD

**Issue by forgetso** [prosopo/captcha#99]
Some websites such as [faucets](https://use.ink/faucet/), require very short expiry times before a captcha needs to be completed again. These times are typically <= 1min. We need to make it easy for website to implement prosopo captcha with configured expiry times instead of leaving the client to query the contract details themselves.

**Comment by HughParry** [comment]
This is now easy to impl

**Comment by forgetso** [comment]
Is this implemented in terms of 

- frontend
- backend
- contract
?

**Comment by HughParry** [comment]
Already implemented in frontend via 

```
    const setValidChallengeTimeout = () => {
        console.log('setting valid challenge timeout')
        const timeMillis: number = configOptional.challengeValidLength || 120 * 1000 // default to 2 minutes
        const successfullChallengeTimeout = setTimeout(() => {
            console.log('valid challenge expired after ' + timeMillis + 'ms')

            // Human state expired, disallow user's claim to be human
            updateState({ isHuman: false })

            events.onExpired()
        }, timeMillis)

        updateState({ successfullChallengeTimeout })
    }
```

The client just has to set challengeValidLength to the desired value

**Comment by HughParry** [comment]
https://github.com/prosopo/captcha/pull/780/files
